#ifndef HTML_META_H
#define HTML_META_H

#include "html_common.h"

#define HASH #
#define DEFINE HASH define
#define IFNDEF HASH ifndef
#define ENDIF HASH endif

#define HTML_TAG0(name, type) DEFINE HTML_NAME(name)(...) HTML_PRINT_TAG(HTML_STR(name), type, __VA_ARGS__)
#define HTML_TAG(name) HTML_TAG0(name, HTML_NORMAL)
#define HTML_TAGS(name) HTML_TAG0(name, HTML_SCLOSE)
#define HTML_TAGN(name) HTML_TAG0(name, HTML_NCLOSE)

IFNDEF HTML_META_I
DEFINE HTML_META_I

/* Naively extracted from https://github.com/mdn/content/tree/main/files/en-us/web/html/element */
HTML_TAG(a)
HTML_TAG(abbr)
HTML_TAG(acronym)
HTML_TAG(address)
HTML_TAG(applet)
HTML_TAG(aside)
HTML_TAG(audio)
HTML_TAG(b)
HTML_TAG(basefont)
HTML_TAG(bdi)
HTML_TAG(bdo)
HTML_TAG(bgsound)
HTML_TAG(big)
HTML_TAG(blink)
HTML_TAG(blockquote)
HTML_TAG(body)
HTML_TAG(button)
HTML_TAG(caption)
HTML_TAG(center)
HTML_TAG(cite)
HTML_TAG(code)
HTML_TAG(data)
HTML_TAG(datalist)
HTML_TAG(dd)
HTML_TAG(del)
HTML_TAG(details)
HTML_TAG(dfn)
HTML_TAG(dialog)
HTML_TAG(dir)
HTML_TAG(div)
HTML_TAG(dl)
HTML_TAG(dt)
HTML_TAG(em)
HTML_TAG(fieldset)
HTML_TAG(figcaption)
HTML_TAG(figure)
HTML_TAG(font)
HTML_TAG(footer)
HTML_TAG(form)
HTML_TAG(frameset)
HTML_TAG(head)
HTML_TAG(header)
HTML_TAG(heading_elements)
HTML_TAG(hgroup)
HTML_TAG(i)
HTML_TAG(iframe)
HTML_TAG(image)
HTML_TAG(ins)
HTML_TAG(kbd)
HTML_TAG(label)
HTML_TAG(map)
HTML_TAG(marquee)
HTML_TAG(menu)
HTML_TAG(meter)
HTML_TAG(nav)
HTML_TAG(nobr)
HTML_TAG(noembed)
HTML_TAG(noframes)
HTML_TAG(noscript)
HTML_TAG(optgroup)
HTML_TAG(output)
HTML_TAG(p)
HTML_TAG(picture)
HTML_TAG(plaintext)
HTML_TAG(portal)
HTML_TAG(pre)
HTML_TAG(progress)
HTML_TAG(q)
HTML_TAG(rb)
HTML_TAG(rp)
HTML_TAG(rt)
HTML_TAG(rtc)
HTML_TAG(ruby)
HTML_TAG(script)
HTML_TAG(section)
HTML_TAG(select)
HTML_TAG(shadow)
HTML_TAG(slot)
HTML_TAG(spacer)
HTML_TAG(span)
HTML_TAG(strong)
HTML_TAG(style)
HTML_TAG(sub)
HTML_TAG(summary)
HTML_TAG(sup)
HTML_TAG(table)
HTML_TAG(tbody)
HTML_TAG(td)
HTML_TAG(template)
HTML_TAG(textarea)
HTML_TAG(th)
HTML_TAG(time)
HTML_TAG(tr)
HTML_TAG(tt)
HTML_TAG(u)
HTML_TAG(ul)
HTML_TAG(var)
HTML_TAG(video)
HTML_TAG(xmp)

HTML_TAGS(area)
HTML_TAGS(base)
HTML_TAGS(br)
HTML_TAGS(col)
HTML_TAGS(embed)
HTML_TAGS(hr)
HTML_TAGS(img)
HTML_TAGS(input)
HTML_TAGS(link)
HTML_TAGS(meta)
HTML_TAGS(param)
HTML_TAGS(source)
HTML_TAGS(track)
HTML_TAGS(wbr)
HTML_TAGS(command)
HTML_TAGS(keygen)
HTML_TAGS(menuitem)

/* Workaround for obvious reasons */
#ifdef HTML_PREFIX
HTML_TAG(main)
#else
HTML_TAG(html_main)
#endif /* !HTML_PREFIX */

DEFINE HTML_NAME(root)(...) HTML_PRINT_TAG("html", HTML_NORMAL, __VA_ARGS__)
DEFINE HTML_NAME(doctype)(...) HTML_PRINT_TAG("!DOCTYPE html", HTML_NCLOSE, __VA_ARGS__)

ENDIF /* !HTML_META_I */

#endif /* !HTML_META_H */
