#ifndef HTML_META_H
#define HTML_META_H

#include "html_common.h"

#ifdef PREFIX
#define HTML_CAT1(a, b) a##b
#else
#define HTML_CAT1(a, b) b
#endif /* PREFIX */

#define HTML_CAT0(a, b) HTML_CAT1(a, b)
#define HTML_CAT(a, b) HTML_CAT0(a, b)

#define HTML_TAG(name) DEFINE HTML_CAT(PREFIX, name)(...) HTML_PRINT_TAG(HTML_STR(name), __VA_ARGS__)

IFNDEF HTML_META_I
DEFINE HTML_META_I
/* Naively extracted from https://github.com/mdn/content/tree/main/files/en-us/web/html/element */
HTML_TAG(a)
HTML_TAG(abbr)
HTML_TAG(acronym)
HTML_TAG(address)
HTML_TAG(applet)
HTML_TAG(area)
HTML_TAG(aside)
HTML_TAG(audio)
HTML_TAG(b)
HTML_TAG(base)
HTML_TAG(basefont)
HTML_TAG(bdi)
HTML_TAG(bdo)
HTML_TAG(bgsound)
HTML_TAG(big)
HTML_TAG(blink)
HTML_TAG(blockquote)
HTML_TAG(body)
HTML_TAG(br)
HTML_TAG(button)
HTML_TAG(caption)
HTML_TAG(center)
HTML_TAG(cite)
HTML_TAG(code)
HTML_TAG(col)
HTML_TAG(data)
HTML_TAG(datalist)
HTML_TAG(dd)
HTML_TAG(del)
HTML_TAG(details)
HTML_TAG(dfn)
HTML_TAG(dialog)
HTML_TAG(dir)
HTML_TAG(div)
HTML_TAG(dl)
HTML_TAG(dt)
HTML_TAG(em)
HTML_TAG(embed)
HTML_TAG(fieldset)
HTML_TAG(figcaption)
HTML_TAG(figure)
HTML_TAG(font)
HTML_TAG(footer)
HTML_TAG(form)
HTML_TAG(frameset)
HTML_TAG(head)
HTML_TAG(header)
HTML_TAG(heading_elements)
HTML_TAG(hgroup)
HTML_TAG(hr)
HTML_TAG(html)
HTML_TAG(i)
HTML_TAG(iframe)
HTML_TAG(image)
HTML_TAG(img)
HTML_TAG(input)
HTML_TAG(ins)
HTML_TAG(kbd)
HTML_TAG(keygen)
HTML_TAG(label)
/* Workaround for obvious reasons */
#ifdef PREFIX
HTML_TAG(main)
#else
HTML_TAG(html_main)
#endif /* !PREFIX */
HTML_TAG(map)
HTML_TAG(marquee)
HTML_TAG(menu)
HTML_TAG(meta)
HTML_TAG(meter)
HTML_TAG(nav)
HTML_TAG(nobr)
HTML_TAG(noembed)
HTML_TAG(noframes)
HTML_TAG(noscript)
HTML_TAG(optgroup)
HTML_TAG(output)
HTML_TAG(p)
HTML_TAG(param)
HTML_TAG(picture)
HTML_TAG(plaintext)
HTML_TAG(portal)
HTML_TAG(pre)
HTML_TAG(progress)
HTML_TAG(q)
HTML_TAG(rb)
HTML_TAG(rp)
HTML_TAG(rt)
HTML_TAG(rtc)
HTML_TAG(ruby)
HTML_TAG(script)
HTML_TAG(section)
HTML_TAG(select)
HTML_TAG(shadow)
HTML_TAG(slot)
HTML_TAG(source)
HTML_TAG(spacer)
HTML_TAG(span)
HTML_TAG(strong)
HTML_TAG(style)
HTML_TAG(sub)
HTML_TAG(summary)
HTML_TAG(sup)
HTML_TAG(table)
HTML_TAG(tbody)
HTML_TAG(td)
HTML_TAG(template)
HTML_TAG(textarea)
HTML_TAG(th)
HTML_TAG(time)
HTML_TAG(tr)
HTML_TAG(track)
HTML_TAG(tt)
HTML_TAG(u)
HTML_TAG(ul)
HTML_TAG(var)
HTML_TAG(video)
HTML_TAG(wbr)
HTML_TAG(xmp)
ENDIF /* !HTML_META_I */

#endif /* !HTML_META_H */
